services:
  image-classifier:
    image: kaushalkirpekar/DP_docker1:latest  # Replace with your image name and tag
    volumes:
      - /tmp/DPinput/inputdata:/app/input
      - /tmp/DPoutput:/app/output
