services:
  image-classifier:
    image: ghcr.io/datakaveri/differential-privacy:1.0.1 # image name and tag
    volumes:
      - /tmp/DPinput/inputdata:/app/data
      - /tmp/DPinput/config:/app/config
      - /tmp/DPoutput:/app/pipelineOutput
